# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.10

-   repo: https://gitlab.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      language_version: python3.10

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
      language_version: python3.10

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
    -   id: mypy
        args:
            - --strict
            - --ignore-missing-imports
            - --disable-error-code=misc
            - --disable-error-code=type-arg
        language_version: python3.10

-   repo: https://github.com/dosisod/refurb
    rev: 'v1.17.0'
    hooks:
      - id: refurb
        language_version: python3.10

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
    -   id: pyupgrade
