services:
  db:
    image: mysql:5.7
    container_name: gpc-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "gpc"
      MYSQL_ROOT_PASSWORD: "test1234"
    volumes:
      - ./.db/mysql:/var/lib/mysql:rw
      - ./docker/mysql/conf.d:/etc/mysql/mysql.conf.d:ro
